### ISSUE TITLE
Reinstate Batching JS test

### ISSUE THREAD

**Issue by simonziegler** [simonziegler/BlazorMdc#558]
I disabled the batching js test because it failed due to not having a context available against which to run `StateHasChanged()` in https://github.com/Material-Blazor/Material.Blazor/blob/main/Material.Blazor.Test/BatchingExceptionPropagation.cs#L22

**Comment by stefanloerwald** [comment]
This test cannot be easily fixed, as it now tries to use the blazor framework lifecycle which is not working when the component instance is `new`ed instead of created by the blazor framework. Either the code needs to stop doing this, or the test needs to use the blazor framework (e.g. using bunit), or the test needs to be removed.

**Comment by MarkStega** [comment]
Since batching js is now just a memory of a failed experiment this issue is no longer relevant,,,
