### ISSUE TITLE
Autocomplete menu placement error

### ISSUE THREAD

**Issue by MarkStega** [simonziegler/BlazorMdc#589]
**From mrpmorris on Element:**  On a phone (S7 Edge) try the auto complete edit with the edit at the bottom of the screen. As my keyboard appears the page scrolls up but the pop-up stays where it is so it's not visible

****Note:** This does not occur on a Galaxy S10 using Chrome

**Comment by simonziegler** [comment]
@mrpmorris, Mark has opened this issue for what you found with your mobile phone and the MB Autocomplete. Is there any chance you could perhaps post a video, because we don't have the same kit at you to experience the issue.

We think this could be an environment issue with with Galaxy S7/Edge.

Thanks,    Simon

**Comment by simonziegler** [comment]
@mrpmorris reports that this is no longer an issue
