### ISSUE TITLE
MBButton ignoring IconFoundry?

### ISSUE THREAD

**Issue by MichelMichels** [simonziegler/BlazorMdc#609]
**Describe the bug**
I have a suspicion that the IconFoundy property on MBButton is completely ignored.

**To Reproduce**
Change the IconFoundry to "@MBIconHelper.FAFoundry()" and the LeadingIcon to "fa-microsoft".
Run it, nothing seems to display except for an empty space where the icon should be.

**Expected behavior**
I'd expect the icon to be shown from Font Awesome.

**Environment**
 - Everything is updated to latest version (NuGet, not preview)

**Comment by MarkStega** [comment]
I added a font awesome icon (fa-dog) to our button demo (locally, not committed) and it works as expected. I am guessing that you don't have the font awesome icons loaded. They are optional (see the installation article for details).

[Edit] I decided to totally repro your original report, changed fa-dog to fa-microsoft and there is indeed a space instead of an icon. Apparently fa-microsoft is not in the free icon set so you need to load whatever premium set that includes that icon..

**Comment by MichelMichels** [comment]
> [Edit] I decided to totally repro your original report, changed fa-dog to fa-microsoft and there is indeed a space instead of an icon. Apparently fa-microsoft is not in the free icon set so you need to load whatever premium set that includes that icon..

I didn't think of this. Thanks for the investigation! :)
